// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkPgX1aDOiT5d-V8DcbZ1zKyN5m5yC40',
    appId: '1:658439363868:web:5b13b414c723b879a36ed9',
    messagingSenderId: '658439363868',
    projectId: 'ruet-bus',
    authDomain: 'ruet-bus.firebaseapp.com',
    storageBucket: 'ruet-bus.firebasestorage.app',
    measurementId: 'G-XE5FJSQ5HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIF57F227ShLXQp5u7Wf4OrUrUYD3LA8',
    appId: '1:658439363868:android:b9ae987bf6abb576a36ed9',
    messagingSenderId: '658439363868',
    projectId: 'ruet-bus',
    storageBucket: 'ruet-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_14LWJnvn3kHuItSHnAOdaHxSA63usYg',
    appId: '1:658439363868:ios:93558e3f5356f654a36ed9',
    messagingSenderId: '658439363868',
    projectId: 'ruet-bus',
    storageBucket: 'ruet-bus.firebasestorage.app',
    iosBundleId: 'com.example.simpleBusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_14LWJnvn3kHuItSHnAOdaHxSA63usYg',
    appId: '1:658439363868:ios:93558e3f5356f654a36ed9',
    messagingSenderId: '658439363868',
    projectId: 'ruet-bus',
    storageBucket: 'ruet-bus.firebasestorage.app',
    iosBundleId: 'com.example.simpleBusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOkPgX1aDOiT5d-V8DcbZ1zKyN5m5yC40',
    appId: '1:658439363868:web:43e13fde1eff1300a36ed9',
    messagingSenderId: '658439363868',
    projectId: 'ruet-bus',
    authDomain: 'ruet-bus.firebaseapp.com',
    storageBucket: 'ruet-bus.firebasestorage.app',
    measurementId: 'G-5QPT5RWB6N',
  );
}
